name: flutterwebapp
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# Versioning of your Flutter app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Set it to the supported Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style design.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for code quality.
  flutter_lints: ^4.0.0

flutter:

  # Ensure the Material Icons font is included.
  uses-material-design: true

  # Assets for the application, like images.
  assets:
    - assets/images/splash_image.jpg
    - assets/images/logo.png

  # Fonts can be added here, if required.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
